# Generated by Django 4.2.5 on 2023-10-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
