# Generated by Django 4.2.5 on 2023-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
