# Generated by Django 4.2.5 on 2023-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0002_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='numero_telefone',
            field=models.CharField(default='123456789', max_length=15),
        ),
    ]
