# Generated by Django 4.2.5 on 2023-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0004_alter_instrumentos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='numero_telefone',
            field=models.CharField(default='5511123456789', max_length=15),
        ),
    ]
