# Generated by Django 4.2.5 on 2023-11-13 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0005_alter_instrumentos_numero_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instrumentos_vistos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_vistos', to='hmusic.instrumentos'),
        ),
    ]
